
server:
  port: ${PORT:8888}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eugenia27/ConfigDataParcial
#          default-label: master
          force-pull: true
#          search-paths: